# Generated by Django 5.0 on 2023-12-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_country_country_name_alter_genra_genra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.card'),
        ),
    ]
