# Generated by Django 5.0 on 2023-12-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_updated_on_alter_card_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_up_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
