# Generated by Django 5.0 on 2024-01-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='card',
        ),
        migrations.AddField(
            model_name='student',
            name='issued_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
