# Generated by Django 5.0 on 2024-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_transaction_card_remove_student_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
